# Generated by Django 2.2.7 on 2020-01-02 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Cliente')),
                ('dui', models.CharField(max_length=15, verbose_name='D.U.I.')),
                ('direccion', models.TextField(verbose_name='Dirreccion')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('documento', models.CharField(max_length=15, verbose_name='Documento')),
                ('val_cargo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cargo')),
                ('val_abono', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Abono')),
                ('val_saldo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cxc.Cliente')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('val_abono', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Abono')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cxc.Cargo')),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
                'ordering': ['id'],
            },
        ),
    ]
