# Generated by Django 3.0.2 on 2020-01-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['id'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='cargo',
            name='val_abono',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Abono'),
        ),
    ]
