# Generated by Django 3.0.2 on 2020-01-28 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Costo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Precio')),
                ('precio_cliente', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Precio Cliente')),
                ('existencia', models.IntegerField(default=0, verbose_name='Existencia')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Consigna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('fecha_recibe', models.DateField(blank=True, null=True, verbose_name='Fecha Recibe')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega')),
                ('viatico', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Viatico')),
                ('penalizacion', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Penalizacion')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('completa', models.BooleanField(verbose_name='Completa')),
            ],
            options={
                'verbose_name': 'Consigna',
                'verbose_name_plural': 'Consignas',
                'ordering': ['id', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('dui', models.CharField(max_length=15, verbose_name='D.U.I.')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Gestor',
                'verbose_name_plural': 'Gestores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Tipo de Articulo')),
            ],
            options={
                'verbose_name': 'Tipo de Articulo',
                'verbose_name_plural': 'Tipos de Articulos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('direccion', models.TextField(verbose_name='Direccion')),
                ('dui', models.CharField(max_length=15, verbose_name='D.U.I.')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleConsigna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Precio')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Total')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consignacion.Articulo')),
                ('consigna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consignacion.Consigna')),
            ],
            options={
                'verbose_name': 'Detalle de Consigna',
                'verbose_name_plural': 'Detalle de Consignas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='consigna',
            name='gestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consignacion.Gestor'),
        ),
        migrations.AddField(
            model_name='consigna',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consignacion.Vendedor'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='TipoArticulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consignacion.TipoArticulo'),
        ),
    ]
